package etc.execption.throw_;

public class ThrowExample {

	static int calcTotal(int num) throws Exception {
		if(num <= 0) {
			System.out.println("매개값은 양수로 주세요!");
			throw new Exception();
		}
		int total = 0;
		for(int i=0; i<=num; i++) {
			total += i;
		}
		return total;
	}
	
	public static void main(String[] args) {

		try {
			System.out.println(calcTotal(100));
			System.out.println(calcTotal(-120));
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		
		
		
	}

}




